# Generated by Django 4.2.30 on 2026-05-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_games', to='collections.collection', verbose_name='Коллекция')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Игра в коллекции',
                'verbose_name_plural': 'Игры в коллекциях',
            },
        ),
    ]
