# Generated by Django 4.2.30 on 2026-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_add_initial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='initial_rating_count',
            field=models.IntegerField(default=0, verbose_name='Количество оценок (RAWG)'),
        ),
    ]
