# Generated by Django 4.2.30 on 2026-06-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_initial_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео (трейлера)'),
        ),
    ]
