# Generated by Django 4.2.30 on 2026-06-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
