# Generated by Django 4.2.30 on 2026-06-02 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000, message='Текст отзыва не может превышать 5000 символов.')], verbose_name='Текст отзыва'),
        ),
    ]
