# Generated by Django 4.2.30 on 2026-06-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_text'),
        ('reviews', '0003_review_score_gameplay_review_score_graphics_and_more'),
    ]

    operations = [
    ]
